from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class IntentEnum(str, Enum):
    RETURNS = "returns"
    GENERAL = "general"


class ActionEnum(str, Enum):
    RESPOND = "respond"
    EXECUTE_WORKFLOW = "execute_workflow"


class ReasonEnum(str, Enum):
    GREETING = "greeting"
    SMALL_TALK = "small_talk"
    MISSING_ORDER_IDENTIFIER = "missing_order_identifier"
    MISSING_CUSTOMER_INFORMATION = "missing_customer_information"
    MISSING_PRODUCT_INFORMATION = "missing_product_information"
    INSUFFICIENT_INFORMATION = "insufficient_information"
    WORKFLOW_READY = "workflow_ready"
    OTHER = "other"


class IntakeOutput(BaseModel):
    """Structured output for classification and triage by the Intake Agent."""
    intent: IntentEnum = Field(
        description="The workflow intent that should handle the request: 'returns' or 'general'."
    )
    action: ActionEnum = Field(
        description="Action to take: 'respond' (reply immediately if info is missing or small talk) or 'execute_workflow' (if downstream execution is required)."
    )
    reason: ReasonEnum = Field(
        description="The debugging/analytical reason for the triage decision."
    )
    response: Optional[str] = Field(
        None,
        description="If action == 'respond', this contains the conversational reply to show the user. If action == 'execute_workflow', this must be null."
    )


class OrderLookupRequest(BaseModel):
    """Request criteria for searching/retrieving orders."""
    order_id: Optional[str] = Field(
        None, description="The unique order ID, e.g., 'TR-4521'."
    )
    customer_name: Optional[str] = Field(
        None, description="The customer's name to search for, e.g., 'Ananya Rao'."
    )
    product_name: Optional[str] = Field(
        None, description="The name of a product to search within order items, e.g., 'Linen Wrap Dress'."
    )


class OrderLookupResponse(BaseModel):
    """Response returned from the Order Lookup tool."""
    success: bool
    orders: List[dict] = Field(
        default_factory=list,
        description="List of orders matching the search criteria."
    )
    message: Optional[str] = None


class PolicyLookupRequest(BaseModel):
    """Query parameter for retrieving company policy information."""
    query: str = Field(
        description="The customer's query or topic regarding store policies, e.g., 'refund timeline' or 'hygiene items'."
    )


class PolicyLookupResponse(BaseModel):
    """Response returned from the Policy Lookup tool."""
    success: bool
    relevant_section: str = Field(
        description="The matching section(s) from the policy document."
    )
    message: Optional[str] = None


class EscalationRequest(BaseModel):
    """Information required to create a human support escalation ticket."""
    reason: str = Field(
        description="The reason for escalation, e.g., 'Lost parcel claim' or 'Payment method COD requires secure link'."
    )
    summary: str = Field(
        description="A concise summary of the conversation context, containing customer details, order numbers, and actions taken so far."
    )


class EscalationResponse(BaseModel):
    """Response returned from the Escalation tool."""
    success: bool
    ticket_id: str = Field(
        description="The unique ticket ID generated for the human handoff."
    )
    reason: str
    message: str = Field(
        description="Notification message to display to the user."
    )


class AgentResponse(BaseModel):
    """Structured response format returned by the support specialists."""
    message: str = Field(
        description="The final agent response or resolution statement to be displayed to the customer."
    )
    requires_escalation: bool = Field(
        default=False,
        description="Set to True if the customer request needs to be escalated to a human agent."
    )
    ticket_id: Optional[str] = Field(
        None,
        description="The ticket ID generated by the Escalation Tool, if escalation was triggered."
    )
